# Generated by Django 2.2 on 2020-02-14 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('semi_tv_shows', '0002_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='desc',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='show',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='networks', to='semi_tv_shows.Network'),
        ),
    ]
